### ISSUE TITLE
More docker build errors

### ISSUE THREAD

**Issue by adamdbrw** [microROS/docker#3]
Following https://github.com/microROS/docker/tree/master/stm32-e407:

CC:  stm32_bringup.c
stm32_bringup.c: In function 'stm32_bringup':
stm32_bringup.c:147:3: warning: implicit declaration of function 'stm32_pmbuttons' [-Wimplicit-function-declaration]
   stm32_pmbuttons();
   ^
CC:  stm32_spi.c
CC:  stm32_autoleds.c
CC:  stm32_buttons.c
CC:  stm32_appinit.c
AR:   stm32_boot.o stm32_bringup.o stm32_spi.o stm32_autoleds.o stm32_buttons.o stm32_appinit.o
make[2]: Leaving directory '/root/nuttx/configs/olimex-stm32-e407/src'
LD: nuttx
/root/nuttx/arch/arm/src/board/libboard.a(stm32_bringup.o): In function `stm32_bringup':
stm32_bringup.c:(.text+0x2): undefined reference to `stm32_pmbuttons'
Makefile:203: recipe for target 'nuttx' failed
make[1]: Leaving directory '/root/nuttx/arch/arm/src'
make[1]: *** [nuttx] Error 1
Makefile.unix:416: recipe for target 'pass2' failed
make: *** [pass2] Error 2
The command '/bin/sh -c export PATH="/root/nuttx/buildroot/build_arm_nofpu/staging_dir/bin/":$PATH && cd nuttx && make' returned a non-zero code: 2
dell@dell-Latitude-E5440:~/git/docker/stm32-e407$ sudo docker build -t microros_stm32f4

**Comment by imuguruza** [comment]
@adamdbrw is this error happening at setting up docker container? Meaning when running `docker build -t microros_stm32f4 . ` command
